pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                script {
                    // Clone the Git repository's master branch
                    def gitRepoUrl = 'https://github.com/RahulKakkarath/DevOps.git'

                    checkout([$class: 'GitSCM', 
                        branches: [[name: '*/main']], 
                        userRemoteConfigs: [[url: gitRepoUrl]], 
                        extensions: [[$class: 'CleanBeforeCheckout'], [$class: 'CloneOption', noTags: false, shallow: true, depth: 1]]
                    ])
                }
            }
        }
        stage('Compile') {
            steps {
                // Build your application here (e.g., compile, package, etc.)
                sh '''
                echo "In Compile Step"
                cd Jenkins/Jenkins_Files/maven-samples/single-module
                mvn compile
                '''
            }
        }
        stage('Test') {
            steps {
                // Build your application here (e.g., compile, package, etc.)
                sh '''
                echo "In Test Step"
                cd Jenkins/Jenkins_Files/maven-samples/single-module
                mvn test
                '''
            }
        }
        stage('Build') {
            steps {
                // Build your application here (e.g., compile, package, etc.)
                sh '''
                echo "In Build Step"
                cd Jenkins/Jenkins_Files/maven-samples/single-module
                mvn clean install
                '''
            }
        }
    }
}